//example referencing week 9: beginner[8].tuesday = '3'


const beginner = [
    {
        week: '1',
        monday: 'rest',
        tuesday: '3',
        wednesday: '3',
        thursday: '3',
        friday: 'rest',
        saturday: '6',
        sunday: 'rest',
    },
    {
        week: '2',
        monday: 'rest',
        tuesday: '3',
        wednesday: '3',
        thursday: '3',
        friday: 'rest',
        saturday: '7',
        sunday: 'rest',
    },
    {
        week: '3',
        monday: 'rest',
        tuesday: '3',
        wednesday: '4',
        thursday: '3',
        friday: 'rest',
        saturday: '5',
        sunday: 'rest',
    },
    {
        week: '4',
        monday: 'rest',
        tuesday: '3',
        wednesday: '4',
        thursday: '3',
        friday: 'rest',
        saturday: '9',
        sunday: 'rest',
    },
    {
        week: '5',
        monday: 'rest',
        tuesday: '3',
        wednesday: '5',
        thursday: '3',
        friday: 'rest',
        saturday: '10',
        sunday: 'rest',
    },
    {
        week: '6',
        monday: 'rest',
        tuesday: '3',
        wednesday: '5',
        thursday: '3',
        friday: 'rest',
        saturday: '7',
        sunday: 'rest',
    },
    {
        week: '7',
        monday: 'rest',
        tuesday: '3',
        wednesday: '6',
        thursday: '3',
        friday: 'rest',
        saturday: '12',
        sunday: 'rest',
    },
    {
        week: '8',
        monday: 'rest',
        tuesday: '3',
        wednesday: '6',
        thursday: '3',
        friday: 'rest',
        saturday: 'rest',
        sunday: '13',
    },
    {
        week: '9',
        monday: 'rest',
        tuesday: '3',
        wednesday: '7',
        thursday: '4',
        friday: 'rest',
        saturday: '10',
        sunday: 'rest',
    },
    {
        week: '10',
        monday: 'rest',
        tuesday: '3',
        wednesday: '7',
        thursday: '4',
        friday: 'rest',
        saturday: '15',
        sunday: 'rest',
    },
    {
        week: '11',
        monday: 'rest',
        tuesday: '4',
        wednesday: '8',
        thursday: '4',
        friday: 'rest',
        saturday: '16',
        sunday: 'rest',
    },
    {
        week: '12',
        monday: 'rest',
        tuesday: '4',
        wednesday: '8',
        thursday: '5',
        friday: 'rest',
        saturday: '12',
        sunday: 'rest',
    },
    {
        week: '13',
        monday: 'rest',
        tuesday: '4',
        wednesday: '9',
        thursday: '5',
        friday: 'rest',
        saturday: '18',
        sunday: 'rest',
    },
    {
        week: '14',
        monday: 'rest',
        tuesday: '5',
        wednesday: '9',
        thursday: '5',
        friday: 'rest',
        saturday: '14',
        sunday: 'rest',
    },
    {
        week: '15',
        monday: 'rest',
        tuesday: '5',
        wednesday: '10',
        thursday: '5',
        friday: 'rest',
        saturday: '20',
        sunday: 'rest',
    },
    {
        week: '16',
        monday: 'rest',
        tuesday: '5',
        wednesday: '8',
        thursday: '4',
        friday: 'rest',
        saturday: '12',
        sunday: 'rest',
    },
    {
        week: '17',
        monday: 'rest',
        tuesday: '4',
        wednesday: '6',
        thursday: '3',
        friday: 'rest',
        saturday: '8',
        sunday: 'rest',
    },
    {
        week: '18',
        monday: 'rest',
        tuesday: '3',
        wednesday: '4',
        thursday: '2',
        friday: 'rest',
        saturday: 'rest',
        sunday: '26.2',
    },
]

module.exports = beginner
