const intermediate = [
    {
        week: '1',
        monday: '3',
        tuesday: '3',
        wedneday: '5',
        thursday: '7',
        friday: 'rest',
        saturday: '2',
        sunday: '10',
    },
    {
        week: '2',
        monday: '3',
        tuesday: '7',
        wedneday: '3',
        thursday: '3',
        friday: 'rest',
        saturday: '5',
        sunday: '11',
    },
    {
        week: '3',
        monday: '3',
        tuesday: '5',
        wedneday: '3',
        thursday: '7',
        friday: 'rest',
        saturday: '6',
        sunday: '13',
    },
    {
        week: '4',
        monday: '3',
        tuesday: '4',
        wedneday: '3',
        thursday: '8',
        friday: 'rest',
        saturday: '2',
        sunday: '13',
    },
    {
        week: '5',
        monday: 'rest',
        tuesday: '3',
        wedneday: '8',
        thursday: '3',
        friday: 'rest',
        saturday: '2',
        sunday: '14',
    },
    {
        week: '6',
        monday: '3',
        tuesday: '3',
        wedneday: '6',
        thursday: '8',
        friday: 'rest',
        saturday: '2',
        sunday: '10',
    },
    {
        week: '7',
        monday: '3',
        tuesday: '5',
        wedneday: '3',
        thursday: '9',
        friday: 'rest',
        saturday: '3',
        sunday: '16',
    },
    {
        week: '8',
        monday: '3',
        tuesday: '9',
        wedneday: '4',
        thursday: '7',
        friday: 'rest',
        saturday: '3',
        sunday: '17',
    },
    {
        week: '9',
        monday: '4',
        tuesday: '6',
        wedneday: '4',
        thursday: '9',
        friday: 'rest',
        saturday: 'rest',
        sunday: '13',
    },
    {
        week: '10',
        monday: 'rest',
        tuesday: '4',
        wedneday: '9',
        thursday: '4',
        friday: 'rest',
        saturday: '9',
        sunday: '19',
    },
    {
        week: '11',
        monday: '4',
        tuesday: '10',
        wedneday: '5',
        thursday: '4',
        friday: 'rest',
        saturday: '3',
        sunday: '20',
    },
    {
        week: '12',
        monday: '4',
        tuesday: '7',
        wedneday: '5',
        thursday: '10',
        friday: 'rest',
        saturday: '2',
        sunday: '12',
    },
    {
        week: '13',
        monday: '4',
        tuesday: '5',
        wedneday: '5',
        thursday: '11',
        friday: 'rest',
        saturday: '3',
        sunday: '20',
    },
    {
        week: '14',
        monday: '5',
        tuesday: '9',
        wedneday: '5',
        thursday: '5',
        friday: 'rest',
        saturday: '2',
        sunday: '12',
    },
    {
        week: '15',
        monday: '5',
        tuesday: '8',
        wedneday: '4',
        thursday: '8',
        friday: 'rest',
        saturday: '3',
        sunday: '20',
    },
    {
        week: '16',
        monday: '5',
        tuesday: '6',
        wedneday: '5',
        thursday: '6',
        friday: 'rest',
        saturday: '2',
        sunday: '12',
    },
    {
        week: '17',
        monday: '4',
        tuesday: '6',
        wedneday: '4',
        thursday: '4',
        friday: 'rest',
        saturday: '3',
        sunday: '8',
    },
    {
        week: '18',
        monday: '3',
        tuesday: '4',
        wedneday: '4',
        thursday: 'rest',
        friday: 'rest',
        saturday: '2',
        sunday: '26.2',
    },
]

module.exports = elite